### ISSUE TITLE
great idea, kicks after a few seconds however

### ISSUE THREAD

**Issue by artulloss** [ErkamKahriman/PacketLimiter#1]
please make this work this sounds like exactly what I need. doesn't seem to properly reset rn.

**Comment by Eren5960** [comment]
Because Task not call. I hope Erkam will be fixed.

**Comment by artulloss** [comment]
I have a custom made working version of this in my servers core, can confirm doing this fixes crashing servers from what I can tell, haven't seen any false kicks either, all were sketchy people with the intention of lagging out server.
